version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"
    webserver:
        # image: puckel/docker-airflow:2.0.0
        image: hf-custom-airflow:v1 
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags # share dags 
            - /var/run/docker.sock:/var/run/docker.sock # share host docker with airflow container
            - /usr/bin/docker:/usr/bin/docker # share host docker with airflow container
            - ./shared-data:/usr/local/airflow/data # shared directory between host and airflow
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg # shared directory between host and airflow
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
